if
    if
        if
            if
                if
                    p
                else
                    p
            else
                p
        else
            p
    else
        if
            if
                if
                    p
                else
                    p
            else
                p
        else
            p
else
    p
